services:
  b-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: es01
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    networks:
      - elastic

networks:
  elastic: